# Generated by Django 4.0.6 on 2022-07-24 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('AR', 'Arequipa'), ('CZ', 'Cuzco'), ('AY', 'Ayacucho'), ('JU', 'Juliaca')], max_length=2, verbose_name='Origen')),
                ('destino', models.CharField(choices=[('AR', 'Arequipa'), ('CZ', 'Cuzco'), ('AY', 'Ayacucho'), ('JU', 'Juliaca')], max_length=2, verbose_name='Destino')),
                ('precio', models.DecimalField(decimal_places=4, max_digits=5, null=True, verbose_name='Precio')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('bus', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Bus.bus', verbose_name='Bus')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
    ]
