# Generated by Django 4.0.6 on 2022-08-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ruta', '0002_alter_ruta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(choices=[('AR', 'Arequipa'), ('CZ', 'Cuzco'), ('AY', 'Ayacucho'), ('IC', 'Ica'), ('PU', 'Puno'), ('HU', 'Huanuco')], max_length=2, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(choices=[('AR', 'Arequipa'), ('CZ', 'Cuzco'), ('AY', 'Ayacucho'), ('IC', 'Ica'), ('PU', 'Puno'), ('HU', 'Huanuco')], max_length=2, verbose_name='Origen'),
        ),
    ]
