# Generated by Django 4.0.6 on 2022-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boleta', '0002_alter_boleta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='precioTotal',
        ),
        migrations.AddField(
            model_name='boleta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Precio Unidad'),
        ),
    ]
