# Generated by Django 4.0.6 on 2022-07-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, null=True, verbose_name='Nombre')),
                ('apellidos', models.TextField(max_length=50, null=True, verbose_name='Apellidos')),
                ('dni', models.IntegerField(null=True, verbose_name='DNI')),
                ('foto_conductor', models.ImageField(blank=True, default=None, null=True, upload_to='Conductor/picture', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
            ],
        ),
    ]
