# Generated by Django 4.0.6 on 2022-07-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='apellidos',
            field=models.TextField(max_length=15, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.TextField(max_length=15, null=True, verbose_name='Nombre'),
        ),
    ]
