# Generated by Django 4.0.6 on 2022-07-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0002_alter_conductor_apellidos_alter_conductor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='apellidos',
            field=models.CharField(max_length=20, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre'),
        ),
    ]
