# Generated by Django 4.0.6 on 2022-08-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0003_alter_conductor_apellidos_alter_conductor_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AddField(
            model_name='conductor',
            name='celular',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
    ]
