# Generated by Django 4.0.6 on 2022-08-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0004_alter_conductor_options_conductor_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
