# Generated by Django 4.0.6 on 2022-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_usuario_celular_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.IntegerField(verbose_name='Celular'),
        ),
    ]
