# Generated by Django 4.0.6 on 2022-07-24 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Conductor', '0003_alter_conductor_apellidos_alter_conductor_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, null=True, verbose_name='Bus')),
                ('capacidad', models.IntegerField(null=True, verbose_name='Capacidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Conductor.conductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
