# Generated by Django 4.0.6 on 2022-08-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
